describe('Pizza Order App', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3000/pizza')
    })

    const nameInput = () => cy.get('#name-input')
    const sizeInput = () => cy.get('#size-dropdown')
    const pepperoniCheck = () => cy.get('#pepperoni')
    const olivesCheck = () => cy.get('#olives')
    const ricottaCheck = () => cy.get('#ricotta')
    const jalapenosCheck = () => cy.get('#jalapenos')
    const specialInput = () => cy.get('#special-text')
    const submitButton = () => cy.get('#order-button')

    it('Checking that all elements exist', () => {
        nameInput().should('exist')
        sizeInput().should('exist')
        pepperoniCheck().should('exist')
        olivesCheck().should('exist')
        ricottaCheck().should('exist')
        jalapenosCheck().should('exist')
        specialInput().should('exist')
        submitButton().should('exist')
    })

    it('Checking that that the submit button is originally disabled', () => {
        submitButton()
            .should('be.disabled')
    })
    
    it('Allows all inputs to be filled', () => {
        nameInput()
            .should('have.value', '')
            .type('Christina Yun')
            .should('have.value', 'Christina Yun')
        sizeInput()
            .should('have.value', '')
            .select('Small')
            .should('have.value', 'small')
        pepperoniCheck()
            .should('not.be.checked')
            .check()
            .should('be.checked')
        olivesCheck()
            .should('not.be.checked')
            .check()
            .should('be.checked')
        ricottaCheck()
            .should('not.be.checked')
            .check()
            .should('be.checked')
        jalapenosCheck()
            .should('not.be.checked')
            .check()
            .should('be.checked')
        specialInput()
            .should('have.value', '')
            .type('Please no anchovies')
            .should('have.value', 'Please no anchovies')
    })

    it('Submits the form after all fields are properly filled out, and then empty after submittal', () => {
        nameInput()
            .type('Shreyas Mohan')
        sizeInput()
            .select('Large')
        pepperoniCheck()
            .check()
        olivesCheck()
            .check()
        ricottaCheck()
            .check()
        jalapenosCheck()
            .check()
        specialInput()
            .type('Add a salad')
        submitButton().click()

        nameInput()
            .should('have.value', '')
        sizeInput()
            .should('have.value', '')
        pepperoniCheck()
            .should('not.be.checked')
        olivesCheck()
            .should('not.be.checked')
        ricottaCheck()
            .should('not.be.checked')
        jalapenosCheck()
            .should('not.be.checked')
        specialInput()
            .should('have.value', '')
        submitButton()
            .should('be.disabled')
    })
})